# Generated by Django 4.2.3 on 2023-07-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chryblk", "0003_quandldata_average"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quandldata",
            name="average",
            field=models.FloatField(),
        ),
    ]
