# Generated by Django 4.2.3 on 2023-07-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chryblk", "0004_alter_quandldata_average"),
    ]

    operations = [
        migrations.AddField(
            model_name="quandldata",
            name="recommendation",
            field=models.CharField(default="Hold", max_length=10),
        ),
        migrations.AlterField(
            model_name="quandldata",
            name="average",
            field=models.FloatField(default=0.0),
        ),
    ]
